USE ROLE ACCOUNTADMIN;

-- Runtime role for the Python AI writer/backfill job
CREATE ROLE IF NOT EXISTS AI_APP_ROLE
  COMMENT='Runtime role: read marts + DDL/DML on GA4_DEMO.DEV_MART.AI_INSIGHTS';

-- Read-only role for Power BI (and analysts)
CREATE ROLE IF NOT EXISTS BI_VIEWER_ROLE
  COMMENT='Read-only access to marts incl. AI_INSIGHTS';

GRANT ROLE AI_APP_ROLE   TO ROLE SYSADMIN;
GRANT ROLE BI_VIEWER_ROLE TO ROLE SYSADMIN;

GRANT USAGE, MONITOR ON WAREHOUSE WH_XS TO ROLE AI_APP_ROLE;
GRANT USAGE, MONITOR ON WAREHOUSE WH_XS TO ROLE BI_VIEWER_ROLE;

GRANT USAGE ON DATABASE GA4_DEMO TO ROLE AI_APP_ROLE;
GRANT USAGE ON DATABASE GA4_DEMO TO ROLE BI_VIEWER_ROLE;

-- Marts where your facts & AI table live
GRANT USAGE ON SCHEMA GA4_DEMO.DEV_MART TO ROLE AI_APP_ROLE;
GRANT USAGE ON SCHEMA GA4_DEMO.DEV_MART TO ROLE BI_VIEWER_ROLE;

-- Dev - where DIM_DATE live
GRANT USAGE ON SCHEMA GA4_DEMO.DEV TO ROLE AI_APP_ROLE;
GRANT USAGE ON SCHEMA GA4_DEMO.DEV TO ROLE BI_VIEWER_ROLE;

-- Allow the app role to CREATE tables/views in DEV_MART (needed for first run)
GRANT CREATE TABLE ON SCHEMA GA4_DEMO.DEV_MART TO ROLE AI_APP_ROLE;
GRANT CREATE VIEW  ON SCHEMA GA4_DEMO.DEV_MART TO ROLE AI_APP_ROLE;


GRANT SELECT ON ALL TABLES IN SCHEMA GA4_DEMO.DEV_MART  TO ROLE AI_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GA4_DEMO.DEV_MART TO ROLE AI_APP_ROLE;
GRANT SELECT ON ALL VIEWS  IN SCHEMA GA4_DEMO.DEV_MART  TO ROLE AI_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GA4_DEMO.DEV_MART TO ROLE AI_APP_ROLE;

-- DIM_DATE lives in DEV; give the app role read there as well
GRANT SELECT ON ALL TABLES IN SCHEMA GA4_DEMO.DEV       TO ROLE AI_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GA4_DEMO.DEV    TO ROLE AI_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA GA4_DEMO.DEV        TO ROLE AI_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GA4_DEMO.DEV     TO ROLE AI_APP_ROLE;

-- If the AI_INSIGHTS table already exists, transfer OWNERSHIP to the app role
-- (required for ALTER TABLE in your "ensure_table" step)
GRANT OWNERSHIP ON TABLE GA4_DEMO.DEV_MART.AI_INSIGHTS
TO ROLE AI_APP_ROLE
COPY CURRENT GRANTS;

-- DML on the target table (not strictly needed after ownership, but harmless)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GA4_DEMO.DEV_MART.AI_INSIGHTS TO ROLE AI_APP_ROLE;



GRANT SELECT ON TABLE GA4_DEMO.DEV_MART.AI_INSIGHTS TO ROLE BI_VIEWER_ROLE;
GRANT SELECT ON ALL VIEWS  IN SCHEMA GA4_DEMO.DEV_MART TO ROLE BI_VIEWER_ROLE;
GRANT SELECT ON TABLE GA4_DEMO.DEV.DIM_DATE TO ROLE BI_VIEWER_ROLE;

CREATE USER IF NOT EXISTS AI_WRITER
  PASSWORD = ''  
  DEFAULT_ROLE = AI_APP_ROLE
  DEFAULT_WAREHOUSE = WH_XS
  DEFAULT_NAMESPACE = GA4_DEMO.DEV_MART
  MUST_CHANGE_PASSWORD = TRUE
  COMMENT='Service user for AI insights job';

GRANT ROLE AI_APP_ROLE TO USER AI_WRITER;

CREATE USER IF NOT EXISTS POWERBI_SVC
  PASSWORD = ''
  DEFAULT_ROLE = BI_VIEWER_ROLE
  DEFAULT_WAREHOUSE = WH_XS
  DEFAULT_NAMESPACE = GA4_DEMO.DEV_MART
  MUST_CHANGE_PASSWORD = TRUE
  COMMENT='Read-only user for Power BI';

GRANT ROLE BI_VIEWER_ROLE TO USER POWERBI_SVC;

